[package]
name = "sdl2_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.2", features = ["derive"] }
serde_json = "1.0.1"
base64 = "0.22"
clap = { version = "4.5.16", features = ["derive"] }
sdl2 = { version = "0.37.0", features = ["image", "ttf"] }
